apiVersion: v1
kind: Service
metadata:
  labels:
    app: spoon-admin
  name: spoon-admin
  namespace: spoon
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: spoon-admin