apiVersion: v1
kind: Service
metadata:
  labels:
    app: spoon-backend
  name: spoon-backend
  namespace: spoon
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: spoon-backend