apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
  namespace: spoon
spec:
  selector:
    matchLabels:
      app: mongodb-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express:0.54.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: mongodb-express-config
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "1"

