kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv-volume
  namespace: spoon
  labels:
    type: local
    app: mongodb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/mongodb"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pv-claim
  namespace: spoon
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
