apiVersion: v1
kind: Service
metadata:
  name: mongodb-express
  namespace: spoon
  labels:
    app: mongodb-express
spec:
  type: LoadBalancer
  ports:
   - port: 8081
  selector:
   app: mongodb-express